"""Utilidades compartidas entre CLI, panel Tkinter y empaquetado."""

from tributacos_core.runtime import (
    DEV_BACKEND_PORT,
    DEV_FRONTEND_PORT,
    STANDALONE_PORT,
    DistributionMode,
    backup_dir,
    bundled_root,
    diagnostic_report,
    distribution_mode,
    get_app_url,
    ingest_folders,
    ingest_root,
    is_frozen,
    manual_pdfs,
    open_data_folder,
    open_ingest_folder,
    open_path,
    project_root,
    read_version,
    sqlite_path,
    user_data_dir,
)

__all__ = [
    "DEV_BACKEND_PORT",
    "DEV_FRONTEND_PORT",
    "STANDALONE_PORT",
    "DistributionMode",
    "backup_dir",
    "bundled_root",
    "diagnostic_report",
    "distribution_mode",
    "get_app_url",
    "ingest_folders",
    "ingest_root",
    "is_frozen",
    "manual_pdfs",
    "open_data_folder",
    "open_ingest_folder",
    "open_path",
    "project_root",
    "read_version",
    "sqlite_path",
    "user_data_dir",
]
